name: CI/CD Pipeline

on: 
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout code
      uses: actions/checkout@v4

    - name: Step 2 - Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Step 3 - Install dependencies
      run: npm ci

    - name: Step 4 - Run Prettier
      run: npm run prettier:fix

    - name: Step 5 - Run ESLint
      run: npm run lint:fix

    - name: Step 6 - Run Tests
      run: npm run test

    - name: Step 7 - Build the application
      run: npm run build

    - name: Step 8 - Success message
      run: echo "Pipeline executed without errors"
